name: songs_repository

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: ../cache

  cloud_firestore: ^2.4.0
  rxdart: ^0.27.1
  equatable: ^2.0.0
  firebase_core: ^1.4.0

